SELECT * FROM book;

SELECT * FROM JOB_HISTORY;

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID BETWEEN 150 AND 160;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID >160
GROUP BY 

CREATE TABLE ANIMAL(
ANIMAL_NAME VARCHAR(20),
ANIMAL_AGE NUMBER,
ANIMAL_SPECIES VARCHAR(30),
ANIMAL_SEX CHAR(6)
);

SELECT * FROM ANIMAL;

INSERT INTO ANIMAL VALUES ('무',12,'고양이','F');

INSERT INTO ANIMAL VALUES ('야통',10,'고양이','F');
INSERT INTO ANIMAL VALUES ('삼색',12,'고양이','M');
INSERT INTO ANIMAL VALUES ('콩이',8,'강아지','F');
INSERT INTO ANIMAL VALUES ('통',10,'토끼','M');
INSERT INTO ANIMAL VALUES ('보리',8,'강아지','M');

UPDATE ANIMAL SET ANIMAL_SPECIES = '강아지'
WHERE ANIMAL_NAME = '통';

SELECT * FROM ANIMAL;

SELECT ANIMAL_SPECIES AS 종류 ,COUNT(*) AS 합계
FROM ANIMAL 
GROUP BY ANIMAL_SPECIES;

--
SELECT warehouse_id, WAREHOUSE_NAME, ADDRESS, NVL(FREEZER_YN,N)
FROM FOOD_WAREHOUSE
WHERE WAREHOUSE_NAME = '%경기%'
ORDER BY WAREHOUSE_ID;

SELECT COUNT(*)-COUNT(AGE) AS USERS
FROM USER_INFO

SELECT PT_NAME, PT_NO, GEND_CD, AGE, NVL(TLNO,NONE)
FROM PATIENT
ORDER BY AGE DESC, PT_NAME;

SELECT ROUND(AVG(NVL(LENGTH,10),2) AS AVERAGE_LENGTH
FROM FISH_INFO;

SELECT ID , LENGTH 
FROM FISH_INFO
WHERE ROWNUM <= 10
ORDER BY LENGTH DESC, ID;

SELECT COUNT(*)
FROM FISH_INFO
WHERE LENGTH <= 10;
